licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Controllers/SysFieldController.cs
using My.RolePermission.Common;
using My.RolePermission.Model;
using My.RolePermission.Model.SearchParam;
using My.RolePermission.WebApp.Filter;
using System;
using System.Linq;
using System.Web.Mvc;

namespace My.RolePermission.WebApp.Controllers
{
    /// <summary>
    /// 数据字典
    /// </summary>
    [MyAuthorize]
    public class SysFieldController : BaseController
    {
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 异步加载数据
        /// </summary>
        /// <param name="page">页码</param>
        /// <param name="rows">每页显示的行数</param>
        /// <param name="order">排序字段</param>
        /// <param name="sort">升序asc（默认）还是降序desc</param>
        /// <param name="search">查询条件</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetData(FieldParam fieldParam)
        {
            var queryData = SMFIELDService.LoadSearchEntities(fieldParam);
            return Json(new datagrid
            {
                total = fieldParam.TotalCount,
                rows = queryData.Select(s => new
                {
                    ID = s.ID,
                    MYTEXTS = s.MYTEXTS,
                    PARENTID = s.PARENTID,
                    MYTABLES = s.MYTABLES,
                    MYCOLUMS = s.MYCOLUMS,
                    SORT = s.SORT,
                    REMARK = s.REMARK,
                    CREATETIME = s.CREATETIME,
                    CREATEPERSON = s.CREATEPERSON,
                    UPDATETIME = s.UPDATETIME,
                    UPDATEPERSON = s.UPDATEPERSON
                }
                    )
            });
        }
        /// <summary>
        /// 查看详细
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            SMFIELD item = SMFIELDService.LoadEntities(x=>x.ID==id).FirstOrDefault();
            return View(item);
        }

        /// <summary>
        /// 首次创建
        /// </summary>
        /// <returns></returns>
        public ActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// 创建
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(SMFIELD entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                string currentPerson = GetCurrentAccount().UID;
                entity.CREATETIME = DateTime.Now;
                entity.CREATEPERSON = currentPerson;

                string returnValue = string.Empty;
                
                SMLOG _SMLOG = new SMLOG { OPERATION_TYPE = "N",FUNC_CODE = "010021",USER_ID = UserId,CLASSNAME = this.GetType().ToString() +strCreate};

                if (SMFIELDService.AddEntity(entity)!=null)
                {
                    _SMLOG.REMARK = "数据字典:" + entity.MYTEXTS + Suggestion.InsertSucceed;
                    SMLOGService.AddEntity(_SMLOG);//写入日志 

                    return Json(Suggestion.InsertSucceed);
                }
                else
                {
                    _SMLOG.REMARK = "数据字典的信息:" + returnValue + Suggestion.InsertFail;
                    SMLOGService.AddEntity(_SMLOG);//写入日志 

                    return Json(Suggestion.InsertFail + returnValue); //提示插入失败
                }
            }

            return Json(Suggestion.InsertFail + "，请核对输入的数据的格式"); //提示输入的数据的格式不对 
        }
        /// <summary>
        /// 首次编辑
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns></returns> 
        public ActionResult Edit(int id)
        {
            SMFIELD item = SMFIELDService.LoadEntities(x => x.ID == id).FirstOrDefault();
            return View(item);
        }
        /// <summary>
        /// 提交编辑信息
        /// </summary>
        /// <param name="id">主键</param>
        /// <param name="collection">客户端传回的集合</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(SMFIELD entity)
        {
            if (entity != null && ModelState.IsValid)
            {   //数据校验

                string currentPerson = GetCurrentAccount().UID;
                entity.UPDATETIME = DateTime.Now;
                entity.UPDATEPERSON = currentPerson;

                string returnValue = string.Empty;
                SMLOG _SMLOG = new SMLOG { OPERATION_TYPE = "U", FUNC_CODE = "010022", USER_ID = UserId, CLASSNAME = this.GetType().ToString() +strEdit };

                if (SMFIELDService.EditEntity(entity))
                {
                    _SMLOG.REMARK = "数据字典:" + entity.MYTEXTS + Suggestion.UpdateSucceed;
                    SMLOGService.AddEntity(_SMLOG);//写入日志 

                    return Json(Suggestion.UpdateSucceed); //提示更新成功 
                }
                else
                {
                    _SMLOG.REMARK = "数据字典:" + entity.MYTEXTS + Suggestion.UpdateFail + returnValue;

                    return Json(Suggestion.UpdateFail + returnValue); //提示更新失败
                }
            }
            return Json(Suggestion.UpdateFail + "请核对输入的数据的格式"); //提示输入的数据的格式不对               

        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>   
        [HttpPost]
        public ActionResult Delete(FormCollection collection)
        {
            string returnValue = string.Empty;
            string[] deleteId = collection["query"].GetString().Split(',');
            if (deleteId != null && deleteId.Length > 0)
            {
                SMLOG _SMLOG = new SMLOG { OPERATION_TYPE = "D", FUNC_CODE = "010023", USER_ID = UserId, CLASSNAME = this.GetType().ToString() + strDelete };

                if (deleteId.Length == 1)
                {
                    int delId= int.Parse(deleteId[0]);
                    var entity = SMFIELDService.LoadEntities(x => x.ID == delId).FirstOrDefault();
                    if (SMFIELDService.DeleteEntity(entity))
                    {
                        _SMLOG.REMARK = "数据字典信息的Id为" + deleteId[0] + Suggestion.DeleteSucceed;
                        SMLOGService.AddEntity(_SMLOG);//写入日志 

                        return Json("OK");
                    }
                    else
                    {
                        _SMLOG.REMARK = "数据字典信息的Id为" + deleteId[0] + Suggestion.DeleteSucceed;
                    }
                    SMLOGService.AddEntity(_SMLOG);//写入日志 
                }

                #region 批量删除

                //if (SMFIELDService.DeleteCollection(ref validationErrors, deleteId))
                //{
                //    LogClassModels.WriteServiceLog(Suggestion.DeleteSucceed + "，信息的Id为" + string.Join(",", deleteId), "消息"
                //        );//删除成功，写入日志
                //    return Json("OK");
                //}
                //else
                //{
                //    if (validationErrors != null && validationErrors.Count > 0)
                //    {
                //        validationErrors.All(a =>
                //        {
                //            returnValue += a.ErrorMessage;
                //            return true;
                //        });
                //    }
                //    LogClassModels.WriteServiceLog(Suggestion.DeleteFail + "，信息的Id为" + string.Join(",", deleteId) + "," + returnValue, "消息"
                //        );//删除失败，写入日志
                //}
                #endregion
            }
            return Json(returnValue);
        }

        /// <summary>
        /// 获取树形列表的数据
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAllMetadata(int id=0)
        {
            IQueryable<SMFIELD> rows = SMFIELDService.GetAllMetadata(id);
            if (rows.Any())
            {
                //是否可以省
                return Json(new treegrid
                {
                    rows = rows.Select(s =>
                        new
                        {
                            ID = s.ID
                    ,
                            MYTEXTS = s.MYTEXTS
                    ,
                            _parentId = s.PARENTID
                    ,
                            state = s.SMFIELD1.Any(a => a.PARENTID == s.ID) ? "closed" : null
                    ,
                            MYTABLES = s.MYTABLES
                    ,
                            MYCOLUMS = s.MYCOLUMS
                    ,
                            SORT = s.SORT
                    ,
                            REMARK = s.REMARK
                    ,
                            CREATETIME = s.CREATETIME
                    ,
                            CREATEPERSON = s.CREATEPERSON
                    ,
                            UPDATETIME = s.UPDATETIME
                    ,
                            UPDATEPERSON = s.UPDATEPERSON

                        }
                        ).OrderBy(o => o.ID)
                });
            }
            return Content("[]");
        }

    }
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysField/Create.cshtml
@model My.RolePermission.Model.SMFIELD
@{
    ViewBag.SubTitle = "创建 数据字典";
    Layout = "~/Views/Shared/Save.cshtml";
}
@using (Html.BeginForm((string)ViewBag.FormAction, "SysField",FormMethod.Post,new {id = "form1" }))
{ 
    <table id="tbCreate" class="usertableborder" align="center">
        <tr class="usertablerow1">
            <td class="_width">
                @Html.LabelFor(model => model.MYTEXTS)：
            </td>
            <td>
                <input type="text" name="MYTEXTS" class="easyui-textbox" required="true" missingmessage="不能为空"
                    validtype="length[0,50]" invalidmessage="长度不可超过50" />
            </td>
            <td class="_width">
                <a class="anUnderLine" onclick="showModalOnly('PARENTID','../../SysField');">
                    @Html.LabelFor(model => model.PARENTID)
                </a>
            </td>
            <td class="width6">
                <div id="checkPARENTID">
                </div>
                @Html.HiddenFor(model => model.PARENTID)
            </td>
        </tr>
        <tr class="usertablerow2">
            <td class="_width">
                @Html.LabelFor(model => model.MYTABLES)：
            </td>
            <td>
                <input type="text" name="MYTABLES" class="easyui-textbox" required="true" missingmessage="不能为空"
                    validtype="length[0,50]" invalidmessage="长度不可超过50" />
            </td>
            <td class="_width">
                @Html.LabelFor(model => model.MYCOLUMS)：
            </td>
            <td class="width2">
                <input type="text" name="MYCOLUMS" class="easyui-textbox" required="true" missingmessage="不能为空"
                    validtype="length[0,50]" invalidmessage="长度不可超过50" />
            </td>
        </tr>
               <tr class="usertablerow1">
            <td class="_width">
             @Html.LabelFor(model => model.SORT)：
            </td>
            <td colspan="3" class="width2">
              <input type="text" name="SORT" class="easyui-numberbox" required="true" missingmessage="不能为空"
                    validtype="length[0,3]" invalidmessage="长度不可超过3" />
            </td>
        </tr>
        <tr class="usertablerow2">
            <td class="_width">
                @Html.LabelFor(model => model.REMARK)：
            </td>
            <td colspan="3" style="word-break: break-all; overflow-x:hidden;" class="remark">
                 <textarea style=" width:470px;"  cols="30" name="REMARK" rows="3" class="easyui-validatebox" validType="length[0,200]" invalidMessage="长度不可超过200"></textarea>
            </td>
        </tr>
        <tr class="usertablerow1">
            <td colspan="4" style="text-align: center; height: 30px;">
                <a href='#' onclick='$("form").submit()' class="easyui-linkbutton" data-options="iconCls:'icon-add'">
                    添加</a>
                                                    <a href='#' onclick="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'"> 重置</a> 
                <a href='#' onclick="javascript:formClose();" class="easyui-linkbutton" data-options="iconCls:'icon-undo'"> 取消</a>
            </td>
        </tr>
    </table>
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysField/Edit.cshtml
@model My.RolePermission.Model.SMFIELD
@{
    ViewBag.SubTitle = "修改 数据字典";
    Layout = "~/Views/Shared/Save.cshtml";
}
@using (Html.BeginForm((string)ViewBag.FormAction, "SysField",FormMethod.Post,new {id = "form1" }))
{ 
      @Html.HiddenFor(model => model.ID)
     <table id="tbCreate" class="usertableborder" align="center">
        <tr class="usertablerow1">
            <td class="_width">
                @Html.LabelFor(model => model.MYTEXTS)：
            </td>
            <td>
                <input type="text" value="@Html.ValueFor(model => model.MYTEXTS)" name="MYTEXTS" class="easyui-textbox"  missingmessage="不能为空"
                    validtype="length[0,50]" invalidmessage="长度不可超过50" />
            </td>
            <td class="_width">
                <a class="anUnderLine" onclick="showModalOnly('PARENTID','../../SysField');">
                    @Html.LabelFor(model => model.PARENTID)
                </a>
            </td>
            <td class="width6">
                <div id="checkPARENTID">
                    @if (Model != null)
                    {
                        if (Model.PARENTID != null)
                        {
                    <table id="@Model.PARENTID" class="deleteStyle">
                        <tr>
                            <td>
                                <img alt="删除" title="点击删除" src="../../../Images/deleteimge.png" onclick="deleteTable('@Model.PARENTID','PARENTID');" />
                            </td>
                            <td>
                                @Model.SMFIELD2.MYTEXTS
                            </td>
                        </tr>
                    </table>
                        }
                    }
                </div>
                @Html.HiddenFor(model => model.PARENTID)
            </td>
        </tr>
        <tr class="usertablerow2">
            <td class="_width">
                @Html.LabelFor(model => model.MYTABLES)：
            </td>
            <td>
                <input type="text" name="MYTABLES" value="@Html.ValueFor(model => model.MYTABLES)" class="easyui-textbox"  missingmessage="不能为空"
                    validtype="length[0,50]" invalidmessage="长度不可超过50" />
            </td>
            <td class="_width">
                @Html.LabelFor(model => model.MYCOLUMS)：
            </td>
            <td class="width2">
                <input type="text" name="MYCOLUMS" value="@Html.ValueFor(model => model.MYCOLUMS)" class="easyui-textbox"  missingmessage="不能为空"
                    validtype="length[0,50]" invalidmessage="长度不可超过50" />
            </td>
        </tr>
               <tr class="usertablerow1">
            <td class="_width">
             @Html.LabelFor(model => model.SORT)：
            </td>
            <td colspan="3" class="width2">
              <input type="text" name="SORT" value="@Html.ValueFor(model => model.SORT)" class="easyui-numberbox"  missingmessage="不能为空"
                    validtype="length[0,3]" invalidmessage="长度不可超过3" />
            </td>
        </tr>
        <tr class="usertablerow2">
            <td class="_width">
                @Html.LabelFor(model => model.REMARK)：
            </td>
            <td colspan="3" style="word-break: break-all; overflow-x:hidden;" class="remark">
                 <textarea style=" width:470px;"  cols="30" name="REMARK" rows="3" class="easyui-validatebox" validType="length[0,200]" invalidMessage="长度不可超过200">@Html.ValueFor(model => model.REMARK)</textarea>
            </td>
        </tr>
        <tr class="usertablerow1">
            <td colspan="4" style="text-align: center; height: 30px;">
                <a href='#' onclick='$("form").submit()' class="easyui-linkbutton" data-options="iconCls:'icon-edit'">
                    修改</a>
                                                    <a href='#' onclick="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'"> 重置</a> 
                <a href='#' onclick="javascript:formClose();" class="easyui-linkbutton" data-options="iconCls:'icon-undo'"> 取消</a>
            </td>
        </tr>
    </table>
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysField/Index.cshtml
@model My.RolePermission.Model.SMFIELD
@{
    ViewBag.Title = "字典管理";
}
<table id="flexigridData">
</table>
<!-------------------------创建和修改层---------------------------------->
<div id="myWin"></div>
@section scripts{
     <script type="text/javascript">
      $(function () {

          $('#flexigridData').treegrid({
              title: '数据字典',
              iconCls: 'icon-site',
              //                    url: '/SysField/GetAllMetadata',
              idField: 'ID',
              treeField: 'MYTEXTS',
              singleSelect: true, //是否单选行
              selectOnCheck: true, //选中行时复选框选中
              checkOnSelect: true, //选中复选框时选中行
              rownumbers: true,
              toolbar: [
                    ],

              columns: [[
                    	{ field: 'MYTEXTS', title: '名称', width: 215, sortable: true }

					, { field: 'MYTABLES', title: '@Html.LabelFor(model => model.MYTABLES)', width: 112,sortable: true }
					, { field: 'MYCOLUMS', title: '@Html.LabelFor(model => model.MYCOLUMS)', width: 112 ,sortable: true}
					, { field: 'SORT', title: '@Html.LabelFor(model => model.SORT)', width: 96 }
              					, { field: 'REMARK', title: '@Html.LabelFor(model => model.REMARK)', width: 96 }
              					, { field: 'CREATETIME', title: '@Html.LabelFor(model => model.CREATETIME)', width: 96,
                                   formatter: function (value, rec) {
                                      if (value) {
                                          return dateTimeConvert(value);
                                      } 
                                  } 
              }
              					, { field: 'CREATEPERSON', title: '@Html.LabelFor(model => model.CREATEPERSON)', width: 96 }
              					, { field: 'UPDATETIME', title: '@Html.LabelFor(model => model.UPDATETIME)', width: 96
                                  , formatter: function (value, rec) {
                                      if (value) {
                                          return dateTimeConvert(value);
                                      } 
                                  } 
              }
              					, { field: 'UPDATEPERSON', title: '@Html.LabelFor(model => model.UPDATEPERSON)', width: 96 }
				    ]]
                     ,
              onBeforeLoad: function (row, param) {
                  if (row) {
                      $(this).treegrid('options').url = '/SysField/GetAllMetadata/' + row.ID;
                  } else {
                      $(this).treegrid('options').url = '/SysField/GetAllMetadata';
                  }
              }
          });

          //如果列表页出现在弹出框中，则只显示查询和选择按钮 
          var parent = window.dialogArguments; //获取父页面
          //异步获取按钮          
          if (parent == "undefined" || parent == null) {
              //首先获取iframe标签的id值
              var iframeid = window.parent.$('#tabs').tabs('getSelected').find('iframe').attr("id");

              //然后关闭AJAX相应的缓存
              $.ajaxSetup({
                  cache: false
              });

              //获取按钮值
              $.getJSON("/Home/GetToolbar", { id: iframeid }, function (data) {
                  if (data == null) {
                      return;
                  }
                  $('#flexigridData').datagrid("addToolbarItem", data);

              });

          } else {
              //添加选择按钮
              $('#flexigridData').datagrid("addToolbarItem", [{ "text": "选择", "iconCls": "icon-ok", handler: function () { flexiSelect(); } }]);
          }

      });
      function flexiQuery() {
          $('#flexigridData').treegrid('reload');
      }

      function flexiSelect() {
          var node = $('#flexigridData').treegrid('getSelected');
          if (!node) {
              $.messager.alert('操作提示', '请选择一条数据!', 'warning');
              return false;
          }
          var arr = new Array(0);
          arr.push(node.ID);
          arr.push("^"); //主键列和显示列的分割符 ^ 
          arr.push(node.MYTEXTS);
          //主键列和显示列之间用 ^ 分割   每一项用 , 分割
          if (arr.length == 3) {//一条数据和多于一条
              returnParent(arr.join("&")); //每一项用 & 分割
          }
          return false;
      }
      //导航到查看详细的按钮
      function getView() {
          var arr = $('#flexigridData').treegrid('getSelected');

          if (arr) {
              window.location.href = "/SysField/Details/" + arr.ID;

          } else {
              $.messager.alert('操作提示', '请选择一条数据!', 'warning');
          }
          return false;
      }
      //导航到创建的按钮
      function flexiCreate() {
          //window.location.href = "/SysField/Create";
          showMyWindow("#myWin", "创建字典", "/SysField/Create", 680, 300);
          return false;
      }
      //导航到修改的按钮
      function flexiModify() {

          var arr = $('#flexigridData').treegrid('getSelected');

          if (arr) {
              showMyWindow("#myWin", "修改字典", "/SysField/Edit/" + arr.ID, 680, 300);

          } else {
              $.messager.alert('操作提示', '请选择一条数据!', 'warning');
          }
          return false;
      };
      //删除的按钮
      function flexiDelete() {

          var node = $('#flexigridData').treegrid('getSelected');
          if (!node) {
              $.messager.alert('操作提示', '请选择数据!', 'warning');

          } else {
              $.messager.confirm('操作提示', "确认删除这1项吗？", function (r) {
                  if (r) {
                      $.post("/SysField/Delete", { query: node.ID }, function (res) {
                          if (res == "OK") {
                              remove();
                              $.messager.alert('操作提示', '删除成功!', 'info');
                          }
                          else {
                              if (res == "") {
                                  $.messager.alert('操作提示', '删除失败!请查看该数据与其他模块下的信息的关联，或联系管理员。', 'info');
                              }
                              else {
                                  $.messager.alert('操作提示', res, 'info');
                              }
                          }
                      });
                  }
              });
          }
          return false;
      };

      function remove() {
          var node = $('#flexigridData').treegrid('getSelected');
          if (node) {
              $('#flexigridData').treegrid('remove', node.ID);
          }
      }
    </script> 
   }