licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Controllers/SysOperationController.cs
using My.RolePermission.Model;
using My.RolePermission.Model.SearchParam;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using My.RolePermission.Common.HtmlHelpers;
using My.RolePermission.Common;

namespace My.RolePermission.WebApp.Controllers
{
    /// <summary>
    /// 操作
    /// </summary>
    public class SysOperationController : BaseController
    {
        static string ClassName = "SysOperationController";
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        //[SupportFilter]
        public ActionResult Index(string view)
        {
            return View();
        }

        /// <summary>
        /// 异步加载数据
        /// </summary>
        [HttpPost]
        public JsonResult GetData(OperationParam operationParam)
        {
            int total = 0;
            var queryData = SMFUNCTBService.LoadSearchEntities(operationParam);
            total = operationParam.TotalCount;

            var data = queryData.ToList().Select(s => new
            {
                FUNC_ID = s.FUNC_ID,
                FUNC_NAME = s.FUNC_NAME,
                EVENT_NAME = s.EVENT_NAME,
                ICONIC = s.ICONIC,
                ORDERCODE = s.ORDERCODE,
                PARENTFUNC_CODE = s.PARENTFUNC_CODE,
                STATUS = s.STATUS.GetStatusName(),
                SM_SYSTEM = s.SM_SYSTEM,
                FUNC_CODE = s.FUNC_CODE,
                CLASS_NAME = s.CLASS_NAME
            });

            //构造成Json的格式传递
            var result = new { total = total, rows = data };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 查看详细
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int id)
        {
            SMFUNCTB item = SMFUNCTBService.LoadEntities(f => f.FUNC_ID == id).FirstOrDefault();
            return View(item);
        }

        /// <summary>
        /// 首次创建
        /// </summary>
        /// <returns></returns>
        public ActionResult Create(int? id)
        {
            if (id !=null)
            {
                SMMENUTB entityId = SMMENUTBService.LoadEntities(m => m.ID == id).FirstOrDefault();
                if (entityId != null)
                {
                    SMFUNCTB entity = new SMFUNCTB();
                    entity.SysMenuId = id + '&' + entityId.NAME;
                    return View(entity);
                }
            }

            return View();
        }
        /// <summary>
        /// 创建
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(SMFUNCTB entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                string returnValue = string.Empty;
                SMLOG OperLog = new SMLOG { OPERATION_TYPE = "N", FUNC_CODE = "900011", USER_ID =UserId, CLASSNAME = ClassName +strCreate };
                var result = SMFUNCTBService.AddEntity(entity);

                if (result != null)
                {
                    OperLog.REMARK = "操作的信息:(ID:" + entity.FUNC_ID + "名称：" + entity.FUNC_NAME + ")" + Suggestion.InsertSucceed;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.InsertSucceed);
                }
                else
                {
                    OperLog.REMARK = "操作的信息:" + entity.FUNC_ID + Suggestion.InsertFail + returnValue;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.InsertFail + returnValue); //提示插入失败
                }
            }

            return Json(Suggestion.InsertFail + "，请核对输入的数据的格式"); //提示输入的数据的格式不对 
        }
        /// <summary>
        /// 首次编辑
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns></returns> 
        public ActionResult Edit(int id)
        {
            SMFUNCTB item = SMFUNCTBService.LoadEntities(f=>f.FUNC_ID==id).FirstOrDefault();
            return View(item);
        }
        /// <summary>
        /// 提交编辑信息
        /// </summary>
        /// <param name="id">主键</param>
        /// <param name="collection">客户端传回的集合</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Edit(string id, SMFUNCTB entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                string returnValue = string.Empty;
                SMLOG OperLog = new SMLOG { OPERATION_TYPE = "U", FUNC_CODE = "900012", USER_ID =UserId, CLASSNAME = ClassName +strEdit };
    
                if (SMFUNCTBService.EditEntity(entity))
                {
                    OperLog.REMARK = "操作信息的Id:" + id + Suggestion.UpdateSucceed;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.UpdateSucceed); //提示更新成功 
                }
                else
                {
                    OperLog.REMARK = "操作信息的Id:" + id + Suggestion.UpdateFail;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.UpdateFail + returnValue); //提示更新失败
                }
            }
            return Json(Suggestion.UpdateFail + "请核对输入的数据的格式"); //提示输入的数据的格式不对               

        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>   
        [HttpPost]
        public ActionResult Delete(FormCollection collection)
        {
            string returnValue = string.Empty;
            int[] deleteId = collection["query"].GetString().ToIntList().ToArray<int>();
            if (deleteId != null && deleteId.Length > 0)
            {
                SMLOG OperLog = new SMLOG { OPERATION_TYPE = "D", FUNC_CODE = "900013", USER_ID =UserId, CLASSNAME = ClassName + strDelete };

                if (deleteId.Length == 1)
                {
                    int funcId=deleteId[0];
                    var entity = SMFUNCTBService.LoadEntities(f => f.FUNC_ID == funcId).FirstOrDefault();
                    if (SMFUNCTBService.DeleteEntity(entity))
                    {
                        OperLog.REMARK = "信息的Id为" + deleteId[0] + Suggestion.DeleteSucceed;

                        return Json("OK");
                    }
                    else
                    {
                        OperLog.REMARK = "信息的Id为" + deleteId[0] + Suggestion.DeleteSucceed;
                    }
                    SMLOGService.AddEntity(OperLog);//写入日志 
                }

                #region 批量删除

                //if (OperLog.DeleteCollection(ref validationErrors, deleteId))
                //{
                //    OperLog.REMARK = "操作信息的Id:" + string.Join(",", deleteId) + Suggestion.DeleteSucceed;
                //    LogClassService.WriteServiceLog(OperLog);//写入日志 

                //    return Json("OK");
                //}
                //else
                //{
                //    if (validationErrors != null && validationErrors.Count > 0)
                //    {
                //        validationErrors.All(a =>
                //        {
                //            returnValue += a.ErrorMessage;
                //            return true;
                //        });
                //    }
                //    OperLog.REMARK = "操作信息的Id:" + string.Join(",", deleteId) + Suggestion.DeleteFail + " " + returnValue;
                //    LogClassService.WriteServiceLog(OperLog);//写入日志 
                //}

                #endregion

            }
            return Json(returnValue);
        }

        /// <summary>
        /// 首次设置菜单
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns></returns> 
        public ActionResult SetSysMenu(int id)
        {
            var entity = SMFUNCTBService.LoadEntities(m=>m.FUNC_ID==id).FirstOrDefault();
            ViewData["myname"] = entity.FUNC_NAME;
            return View(entity);
        }

        ///// <summary>
        ///// 设置菜单
        ///// </summary>
        ///// <param name="entity"></param>
        ///// <returns></returns>
        //[HttpPost]
        //public ActionResult SetSysMenu(SMFUNCTB entity)
        //{
        //    if (entity != null)
        //    {
        //        string returnValue = string.Empty;
        //        SMLOG OperLog = new SMLOG { OPERATION_TYPE = "U", FUNC_CODE = "900010", USER_ID =UserId, CLASSNAME = ClassName + ": SetSysMenu" };

        //        if (OperLog.SetSysMenu(ref validationErrors, entity))
        //        {
        //            OperLog.REMARK = "信息的Id:" + entity.FUNC_ID + Suggestion.UpdateSucceed;
        //            SMLOGService.AddEntity(OperLog);//写入日志 

        //            return Json(Suggestion.UpdateSucceed); //提示更新成功 
        //        }
        //        else
        //        {
        //            OperLog.REMARK = "信息的Id:" + entity.FUNC_ID + Suggestion.DeleteFail + returnValue;
        //            SMLOGService.AddEntity(OperLog);//写入日志 

        //            return Json(Suggestion.UpdateFail + returnValue);
        //        }
        //    }
        //    else
        //    {
        //        return Json(Suggestion.UpdateFail + "，请核对输入的数据的格式"); //提示输入的数据的格式不对               
        //    }
        //}

    }
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysOperation/Create.cshtml
@model My.RolePermission.Model.SMFUNCTB
@using My.RolePermission.BLL;
@using My.RolePermission.Common;
@{
    ViewBag.SubTitle = "操作 创建";
    Layout = "~/Views/Shared/Save.cshtml";
}
@Html.ValidationSummary(true, "操作创建不成功. 请编辑后重试")
@using (Html.BeginForm((string)ViewBag.FormAction, "SysOperation",FormMethod.Post,new {id = "form1" }))
{ 
    <table id="tbCreate" class="usertableborder" align="center">
        <tr class="usertablerow1">
            <td class="width0">
                @Html.LabelFor(model => model.FUNC_NAME)
            </td>
            <td>
                <input type="text" name="FUNC_NAME" class="easyui-textbox" validtype="length[0,64]"
                    invalidmessage="长度不可超过64" />
            </td>
            <td class="width0">
                @Html.LabelFor(model => model.EVENT_NAME)
            </td>
            <td>
                <input type="text" name="EVENT_NAME" class="easyui-textbox" validtype="length[0,256]"
                    invalidmessage="长度不可超过256" />
            </td>
        </tr>
        <tr class="usertablerow2">
            <td>
                @Html.LabelFor(model => model.ICONIC)
            </td>
            <td>
                <input type="text" name="ICONIC" class="easyui-textbox" validtype="length[0,200]"
                    invalidmessage="长度不可超过200" />
            </td>
            <td>
                @Html.LabelFor(model => model.ORDERCODE)
            </td>
            <td>
                <input type="text" name="ORDERCODE" class="easyui-numberbox" />
            </td>
        </tr>
        <tr class="usertablerow1">
            <td>
                @Html.LabelFor(model => model.CLASS_NAME)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.CLASS_NAME)' name="CLASS_NAME" class="easyui-textbox" validtype="length[0,256]"
                    invalidmessage="长度不可超过256" />
            </td>
                   <td>
                @Html.LabelFor(model => model.STATUS)
            </td>
            <td>
                @Html.DropDownListFor(model => model.STATUS, SelectListClass.GetStatus(true))
            </td>
           
        </tr>
        <tr class="usertablerow2">
            <td>@Html.LabelFor(model => model.FUNC_CODE)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.FUNC_CODE)' name="FUNC_CODE" class="easyui-textbox" validtype="length[0,32]"
                    invalidmessage="长度不可超过32" />
            </td>
            <td>@Html.LabelFor(model => model.PARENTFUNC_CODE)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.PARENTFUNC_CODE)' name="PARENTFUNC_CODE" class="easyui-textbox" validtype="length[0,32]"
                    invalidmessage="长度不可超过32" />
            </td>
        </tr>
        <tr class="usertablerow1">
      <td>
                @Html.LabelFor(model => model.SM_SYSTEM)
            </td>
            <td colspan="3">
                <input type="text"  value='@Html.ValueFor(model => model.SM_SYSTEM)' name="SM_SYSTEM" class="easyui-textbox" validtype="length[0,10]"
                    invalidmessage="长度不可超过10" />
            </td>
        </tr>
         <tr  class="usertablerow2"><td colspan="4" style="text-align:center; height:30px;"> 
                     <a href='#' onclick='$("form").submit()' class="easyui-linkbutton" data-options="iconCls:'icon-add'">添加</a> 
                                                     <a href='#' onclick="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'"> 重置</a> 
                <a href='#' onclick="javascript:formClose();" class="easyui-linkbutton" data-options="iconCls:'icon-undo'"> 取消</a>
          </td></tr>
    </table>
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysOperation/Edit.cshtml
@model My.RolePermission.Model.SMFUNCTB
@using My.RolePermission.BLL;
@using My.RolePermission.Common;
@{
    ViewBag.SubTitle = "操作修改";
    Layout = "~/Views/Shared/Save.cshtml";
}

@Html.ValidationSummary(true, "操作修改不成功. 请编辑后重试")
@using (Html.BeginForm((string)ViewBag.FormAction, "SysOperation",FormMethod.Post,new {id = "form1" }))
{ 
                @Html.HiddenFor(model => model.FUNC_ID)   
      <table id="tbCreate" class="usertableborder" align="center">
        <tr class="usertablerow1">
            <td class="width0">
                @Html.LabelFor(model => model.FUNC_NAME)
            </td>
            <td>
                <input type="text" value='@Html.ValueFor(model => model.FUNC_NAME)' name="FUNC_NAME" class="easyui-textbox" validtype="length[0,64]"
                    invalidmessage="长度不可超过64" />
            </td>
            <td class="width0">
                @Html.LabelFor(model => model.EVENT_NAME)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.EVENT_NAME)' name="EVENT_NAME" class="easyui-textbox" validtype="length[0,256]"
                    invalidmessage="长度不可超过256" />
            </td>
        </tr>
        <tr class="usertablerow2">
            <td>
                @Html.LabelFor(model => model.ICONIC)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.ICONIC)' name="ICONIC" class="easyui-textbox" validtype="length[0,200]"
                    invalidmessage="长度不可超过200" />
            </td>
            <td>
                @Html.LabelFor(model => model.ORDERCODE)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.ORDERCODE)' name="ORDERCODE"  class="easyui-numberbox" />
            </td>
        </tr>
        <tr class="usertablerow1">
            <td>
                @Html.LabelFor(model => model.CLASS_NAME)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.CLASS_NAME)' name="CLASS_NAME" class="easyui-textbox" validtype="length[0,256]"
                    invalidmessage="长度不可超过256" />
            </td>
                   <td>
                @Html.LabelFor(model => model.STATUS)
            </td>
            <td>
                @Html.DropDownListFor(model => model.STATUS, SelectListClass.GetStatus(true))
            </td>
           
        </tr>
        <tr class="usertablerow2">
            <td>@Html.LabelFor(model => model.FUNC_CODE)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.FUNC_CODE)' name="FUNC_CODE" class="easyui-textbox" validtype="length[0,32]"
                    invalidmessage="长度不可超过32" />
            </td>
            <td>@Html.LabelFor(model => model.PARENTFUNC_CODE)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.PARENTFUNC_CODE)' name="PARENTFUNC_CODE" class="easyui-textbox" validtype="length[0,32]"
                    invalidmessage="长度不可超过32" />
            </td>
        </tr>
        <tr class="usertablerow1">
      <td>
                @Html.LabelFor(model => model.SM_SYSTEM)
            </td>
            <td colspan="3">
                <input type="text"  value='@Html.ValueFor(model => model.SM_SYSTEM)' name="SM_SYSTEM" class="easyui-textbox" validtype="length[0,10]"
                    invalidmessage="长度不可超过10" />
            </td>
        </tr>
         <tr  class="usertablerow2"><td colspan="4" style="text-align:center; height:30px;"> 
                     <a href='#' onclick='$("form").submit()' class="easyui-linkbutton" data-options="iconCls:'icon-edit'">修改</a> 
                                                     <a href='#' onclick="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'"> 重置</a> 
                <a href='#' onclick="javascript:formClose();" class="easyui-linkbutton" data-options="iconCls:'icon-undo'"> 取消</a>
          </td></tr>
    </table>
 
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysOperation/Index.cshtml
@model My.RolePermission.Model.SMFUNCTB
@using My.RolePermission.BLL;
@using My.RolePermission.Common;
@{
    ViewBag.Title = "操作管理";
}
<div id="content" region="center" fit="true">
 <div id="divQuery" style="padding: 5px; font-size: 12px;" title="查询列表" class="easyui-toolbar">
    <span>@Html.LabelFor(model => model.FUNC_NAME)</span><input type='text' id='FUNC_NAME' class="easyui-textbox"/>
    <span>@Html.LabelFor(model => model.STATUS)</span> <span>@Html.DropDownListFor(model => model.STATUS,SelectListClass.GetStatus(true),new{@class="easyui-combobox" })</span>
    <a href="javascript:flexiQuery()" class="easyui-linkbutton" data-options="iconCls:'icon-search'">查询</a>
    <a href="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'">重置</a>
           </div>
        <table id="flexigridData">
        </table> 
    <input id="hidtreeid" type="hidden" />
    <input id="SysMenuIdOld" type="hidden" />
</div>
    <!-------------------------创建和修改层---------------------------------->
<div id="myWin"></div>
@section scripts{
        <script type="text/javascript">
            //回车触发查询
            $(function () {
                document.onkeydown = function (e) {
                    var ev = document.all ? window.event : e;
                    if (ev.keyCode == 13) {
                        flexiQuery();
                    }
                }
            });
            $(function () {
                var flag = window.location.search;
                var isSingleSelect = true;
                if (flag == "?view=1") {
                    isSingleSelect = false;
                }
                $('#flexigridData').datagrid({
                    title: '操作', //列表的标题
                    iconCls: 'icon-site',
                    width: 'auto',
                    height: 'auto',
                    singleSelect: isSingleSelect, //是否单选行
                    selectOnCheck: true, //选中行时复选框选中
                    checkOnSelect: true, //选中复选框时选中行
                    nowrap: false,
                    striped: true,
                    collapsible: true,
                    url: 'SysOperation/GetData', //获取数据的url
                    sortName: 'FUNC_ID',
                    sortOrder: 'desc',
                    remoteSort: true, //定义是否从服务器给数据排序。
                    idField: 'FUNC_ID',

                    toolbar: [
                    ],
                    columns: [[
                        { field: 'ck', checkbox: true }, //复选框
                        { field: 'FUNC_NAME', title: '@Html.LabelFor(model => model.FUNC_NAME)', width: 135, sortable: true }
					, { field: 'EVENT_NAME', title: '@Html.LabelFor(model => model.EVENT_NAME)', width: 135, sortable: true }
					, { field: 'ICONIC', title: '@Html.LabelFor(model => model.ICONIC)', width: 135 }
                    , { field: 'CLASS_NAME', title: '@Html.LabelFor(model => model.CLASS_NAME)', width: 135 }
					, { field: 'ORDERCODE', title: '@Html.LabelFor(model => model.ORDERCODE)', width: 60, sortable: true }
                	, { field: 'SM_SYSTEM', title: '@Html.LabelFor(model => model.SM_SYSTEM)', width: 100, sortable: true }
                    , { field: 'STATUS', title: '@Html.LabelFor(model => model.STATUS)', width: 100, sortable: true }
                   , { field: 'FUNC_CODE', title: '@Html.LabelFor(model => model.FUNC_CODE)', width: 100, sortable: true }
					, { field: 'PARENTFUNC_CODE', title: '@Html.LabelFor(model => model.PARENTFUNC_CODE)', width: 100, sortable: true }
                //, { display: '@Html.LabelFor(model => model.SysMenuId)', name: 'SysMenuId', width: 135, sortable: false, align: 'left' }

                ]],
                pagination: true,
                rownumbers: true

            });

            //如果列表页出现在弹出框中，则只显示查询和选择按钮 
            var parent = window.dialogArguments; //获取父页面
            //异步获取按钮          
            if (parent == "undefined" || parent == null) {
                //首先获取iframe标签的id值
                var iframeid = window.parent.$('#tabs').tabs('getSelected').find('iframe').attr("id");

                //然后关闭AJAX相应的缓存
                $.ajaxSetup({
                    cache: false
                });

                //获取按钮值
                $.getJSON("../Home/GetToolbar", { id: iframeid }, function (data) {
                    if (data == null) {
                        return;
                    }
                    $('#flexigridData').datagrid("addToolbarItem", data);

                });

            } else {
                //添加选择按钮
                $('#flexigridData').datagrid("addToolbarItem", [{ "text": "选择", "iconCls": "icon-ok", handler: function () { flexiSelect(); } }]);
            }

            $('#myTree').tree({
                url: '/SysMenuTree/GetTree',
                onClick: function (node) {
                    if (node != null && node.id != null && node.id != "undefined") {
                        if (node.iconCls != null) {//&& node.iconCls == 'icon-ok'
                            $("#hidtreeid").val('');
                            $("#flexigridData").datagrid("load"); //根目录刷新  
                        } else {
                            $("#hidtreeid").val(node.id);
                            $("#flexigridData").datagrid("load", { id: node.id }); //子节点刷新
                        }

                    }
                },
                onBeforeLoad: function (node, param) {
                    if (node) {
                        param.parentid = node.id;
                    }
                }
            });
        });
        //“查询”按钮，弹出查询框
        function flexiQuery() {
            //执行查询                        
            $('#flexigridData').datagrid('reload', { FUNC_NAME: $("#FUNC_NAME").val(), STATUS: $("#STATUS").combobox('getValue') });
        };
        function resetData() {
            $("#FUNC_NAME").textbox('setValue', '')//赋值 
            $("#STATUS").combobox('setValue', '')
        }
        //“选择”按钮，在其他（与此页面有关联）的页面中，此页面以弹出框的形式出现，选择页面中的数据
        function flexiSelect() {
            var rows = $('#flexigridData').datagrid('getSelections');
            if (rows.length == 0) {
                $.messager.alert('操作提示', '请选择数据!', 'warning');
                return false;
            }

            var arr = [];
            for (var i = 0; i < rows.length; i++) {
                arr.push(rows[i].FUNC_ID);
            }
            arr.push("^");
            for (var j = 0; j < rows.length; j++) {
                arr.push(rows[j].FUNC_NAME);
            }

            //主键列和显示列之间用 ^ 分割   每一项用 , 分割
            if (arr.length > 0) {//一条数据和多于一条
                returnParent(arr.join("&")); //每一项用 & 分割
            }
        }
        //导航到查看详细的按钮
        function getView() {
            var arr = $('#flexigridData').datagrid('getSelections');
            if (arr.length == 1) {
                window.location.href = "/SysOperation/Details/" + arr[0].FUNC_ID;

            } else {
                $.messager.alert('操作提示', '请选择一条数据!', 'warning');
            }
            return false;
        }
        //导航到创建的按钮
        function flexiCreate() {
            showMyWindow("#myWin", "操作创建", "/SysOperation/Create", 680, 304);
            return false;
        }
        //导航到修改的按钮
        function flexiModify() {
            var arr = $('#flexigridData').datagrid('getSelections');
            if (arr.length == 1) {
                showMyWindow("#myWin", "操作修改", "/SysOperation/Edit/" + arr[0].FUNC_ID, 680, 304);

            } else {
                $.messager.alert('操作提示', '请选择一条数据!', 'warning');
            }
            return false;

        };
        //删除的按钮
        function flexiDelete() {

            var rows = $('#flexigridData').datagrid('getSelections');
            if (rows.length == 0) {
                $.messager.alert('操作提示', '请选择数据!', 'warning');
                return false;
            }

            var arr = [];
            for (var i = 0; i < rows.length; i++) {
                arr.push(rows[i].FUNC_ID);
            }

            $.messager.confirm('操作提示', "确认删除这 " + arr.length + " 项吗？", function (r) {
                if (r) {
                    $.post("/SysOperation/Delete", { query: arr.join(",") }, function (res) {
                        if (res == "OK") {
                            //移除删除的数据
                            $("#flexigridData").datagrid("reload");
                            $("#flexigridData").datagrid("clearSelections");
                            $.messager.alert('操作提示', '删除成功!', 'info');
                        }
                        else {
                            if (res == "") {
                                $.messager.alert('操作提示', '删除失败!请查看该数据与其他模块下的信息的关联，或联系管理员。', 'info');
                            }
                            else {
                                $.messager.alert('操作提示', res, 'info');
                            }
                        }
                    });
                }
            });
        };

        //设置
        function setSysMenu() {
            var arr = $('#flexigridData').datagrid('getSelections');
            if (arr.length == 1) {
                window.location.href = "../SysOperation/SetSysMenu/" + arr[0].FUNC_ID;
            } else {
                $.messager.alert('操作提示', '请选择一条数据!', 'warning');
            }
            return false;
        }
    </script>
}