licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Controllers/SysMenuController.cs
using My.RolePermission.Common;
using My.RolePermission.Model;
using My.RolePermission.Model.SearchParam;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace My.RolePermission.WebApp.Controllers
{
    /// <summary>
    /// 菜单
    /// </summary>
    public class SysMenuController : BaseController
    {
        string ClassName = "SysMenuController";
        /// <summary>
        /// 列表
        /// </summary>
        /// <returns></returns>
        //[CompressFilter]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 异步加载数据
        /// </summary>
        /// <param name="page">页码</param>
        /// <param name="rows">每页显示的行数</param>
        /// <param name="order">排序字段</param>
        /// <param name="sort">升序asc（默认）还是降序desc</param>
        /// <param name="search">查询条件</param>
        /// <returns></returns>
        [HttpPost]
        //[SupportFilter]
        public JsonResult GetData(MenuParam menuParam)
        {
            int total = 0;
            var queryData = SMMENUTBService.LoadSearchEntities(menuParam);
            total = menuParam.TotalCount;

            //构造成Json的格式传递
            var result = new { total = total, rows = queryData };
            return Json(result, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// 查看详细
        /// </summary> SMLOGService.AddEntity
        /// <param name="id"></param>
        /// <returns></returns>
        //[SupportFilter]
        public ActionResult Details(int id)
        {
            SMMENUTB item = SMMENUTBService.LoadEntities(m => m.ID == id).FirstOrDefault();
            item.STATE = item.STATE == "Y" ? "启用" : "禁用";

            return View(item);
        }

        /// <summary>
        /// 首次创建
        /// </summary>
        /// <returns></returns>
        //[SupportFilter]
        public ActionResult Create()
        {
            return View();
        }
        /// <summary>
        /// 创建
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        [HttpPost]
        //[SupportFilter]
        public ActionResult Create(SMMENUTB entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                entity.CREATETIME = DateTime.Now;
                entity.CREATEPERSON = GetCurrentAccount().USER_NAME;

                string returnValue = string.Empty;

                SMLOG OperLog = new SMLOG { OPERATION_TYPE = "N", FUNC_CODE = "900001", USER_ID =UserId, CLASSNAME = ClassName +strCreate };
                var result = SMMENUTBService.Create(entity);

                if (result!=null)
                {
                    OperLog.REMARK = "菜单:" + entity.NAME + Suggestion.InsertSucceed;

                    SMLOGService.AddEntity(OperLog);//写入日志 
                    return Json(Suggestion.InsertSucceed);
                }
                else
                {
                    OperLog.REMARK = "菜单:" + entity.NAME + Suggestion.InsertFail;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.InsertFail + returnValue); //提示插入失败
                }
            }

            return Json(Suggestion.InsertFail + "，请核对输入的数据的格式"); //提示输入的数据的格式不对 
        }
        /// <summary>
        /// 首次编辑
        /// </summary>
        /// <param name="id">主键</param>
        /// <returns></returns> 
        //[SupportFilter]
        public ActionResult Edit(int id)
        {
            SMMENUTB item = SMMENUTBService.LoadEntities(m => m.ID == id).FirstOrDefault();

            return View(item);
        }
        /// <summary>
        /// 提交编辑信息
        /// </summary>
        /// <param name="id">主键</param>
        /// <param name="collection">客户端传回的集合</param>
        /// <returns></returns>
        [HttpPost]
        //[SupportFilter]
        public ActionResult Edit(string id, SMMENUTB entity)
        {
            if (entity != null && ModelState.IsValid)
            {   //数据校验
                entity.UPDATETIME = DateTime.Now;
                entity.UPDATEPERSON = GetCurrentAccount().USER_NAME;

                string returnValue = string.Empty;

                SMLOG OperLog = new SMLOG { OPERATION_TYPE = "U", FUNC_CODE = "900002", USER_ID =UserId, CLASSNAME = ClassName +strEdit };

                if (SMMENUTBService.Edit(entity))
                {
                    OperLog.REMARK = "菜单:" + entity.NAME + Suggestion.UpdateSucceed;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.UpdateSucceed); //提示更新成功 
                }
                else
                {
                    OperLog.REMARK = "菜单:" + entity.NAME + Suggestion.UpdateFail;
                    SMLOGService.AddEntity(OperLog);//写入日志 

                    return Json(Suggestion.UpdateFail + returnValue); //提示更新失败
                }
            }
            return Json(Suggestion.UpdateFail + "请核对输入的数据的格式"); //提示输入的数据的格式不对               

        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="collection"></param>
        /// <returns></returns>   
        [HttpPost]
        //[SupportFilter]
        public ActionResult Delete(FormCollection collection)
        {
            string returnValue = string.Empty;
            List<int> lists = collection["query"].GetString().ToIntList();
            int[] deleteIds = lists.ToArray();

            if (deleteIds != null && deleteIds.Length > 0)
            {
                SMLOG OperLog = new SMLOG { OPERATION_TYPE = "D", FUNC_CODE = "900003", USER_ID =UserId, CLASSNAME = ClassName + strDelete };

                if (deleteIds.Length == 1)
                {
                    int menuId = deleteIds[0];
                    var entity = SMMENUTBService.LoadEntities(m => m.ID == menuId).FirstOrDefault();
                    if (SMMENUTBService.Delete(entity))
                    {
                        OperLog.REMARK = "菜单Id：" + deleteIds[0] + Suggestion.DeleteSucceed;
                        SMLOGService.AddEntity(OperLog);//写入日志 

                        return Json("OK");
                    }
                    else
                    {
                        OperLog.REMARK = "菜单Id：" + deleteIds[0] + Suggestion.DeleteSucceed;
                    }
                    SMLOGService.AddEntity(OperLog);//写入日志 
                }

                #region 批量删除

                //if (_menuService.DeleteCollection(ref validationErrors, deleteIds))
                //{
                //    OperLog.REMARK = "菜单信息的Id:" + string.Join(",", deleteIds) + Suggestion.DeleteSucceed;
                //    SMLOGService.AddEntity(OperLog);//写入日志 

                //    return Json("OK");
                //}
                //else
                //{
                //    if (validationErrors != null && validationErrors.Count > 0)
                //    {
                //        validationErrors.All(a =>
                //        {
                //            returnValue += a.ErrorMessage;
                //            return true;
                //        });
                //    }
                //    OperLog.REMARK = "菜单信息的Id:" + string.Join(",", deleteIds) + Suggestion.DeleteFail + " " + returnValue;
                //    SMLOGService.AddEntity(OperLog);//写入日志 
                //}
                #endregion
            }
            return Json(returnValue);
        }

        /// <summary>
        /// 获取树形列表的数据
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAllMetadata()
        {
            IQueryable<SMMENUTB> rows = SMMENUTBService.GetAllMetadata();

            if (rows.Any())
            {//是否可以省
                return Json(new treegrid
                {
                    rows = rows.Select(s =>
                        new
                        {
                            ID = s.ID
                    ,
                            NAME = s.NAME
                    ,
                            _parentId = s.PARENTID
                                ,
                            state = s.ISLEAF == "Y" ? "null" : "closed"
                    ,
                            URL = s.URL
                    ,
                            iconCls = s.ICONIC
                    ,
                            SORT = s.SORT
                    ,
                            REMARK = s.REMARK
                    ,
                            STATE = s.STATE == "Y" ? "启用" : "停用"
                    ,
                            CREATEPERSON = s.CREATEPERSON
                    ,
                            CREATETIME = s.CREATETIME
                    ,
                            UPDATETIME = s.UPDATETIME
                    ,
                            UPDATEPERSON = s.UPDATEPERSON

                        }
                        ).OrderBy(o => o.SORT)
                });
            }
            return Content("[]");
        }

        /// <summary>
        /// 获取树形列表的数据
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAllMetadata2(string id)
        {
            var rows = SMMENUTBService.GetAllMetadata().ToList().Select(s =>
                        new
                        {
                            ID = s.ID
                    ,
                            NAME = s.NAME
                    ,
                            _parentId = s.PARENTID
                    ,
                            isCheck = string.Join(",", s.SMFUNCTB.Select(t => t.FUNC_ID + "^" + t.FUNC_NAME))
                    ,
                            iconCls = s.ICONIC

                        }
                        ).OrderBy(o => o.ID);

            return Json(new treegrid() { rows = rows });
        }

        /// <summary>
        /// 获取树形列表的数据
        /// </summary>
        /// <returns></returns>

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysMenu/Create.cshtml
@model My.RolePermission.Model.SMMENUTB
@using My.RolePermission.BLL;
@using My.RolePermission.Common;
@using My.RolePermission.Common.HtmlHelpers;
@{
    ViewBag.SubTitle = "菜单 创建";
    Layout = "~/Views/Shared/Save.cshtml";
}
@Html.ValidationSummary(true, "菜单创建不成功. 请编辑后重试")
@using (Html.BeginForm((string)ViewBag.FormAction, "SysMenu",FormMethod.Post,new {id = "form1" }))
{ 
    <table id="tbCreate" class="usertableborder" align="center">
        <tr class="usertablerow1">
            <td class="_width">
                @Html.LabelFor(model => model.NAME)
            </td>
            <td>
                <input type="text" name="NAME" class="easyui-textbox" required="true" missingmessage="不能为空"
                    validtype="length[0,200]" invalidmessage="长度不可超过200" />
            </td>
            <td class="_width">
                <a class="anUnderLine" onclick="showModalOnly('PARENTID','/SysMenu');">
                    @Html.LabelFor(model => model.PARENTID)
                </a>
            </td>
            <td class="width5">
                <div id="checkPARENTID">
                </div>
                @Html.HiddenFor(model => model.PARENTID)
            </td>
        </tr>
        <tr class="usertablerow2">
            <td>
                @Html.LabelFor(model => model.URL)
            </td>
            <td>
                <input type="text" name="URL" class="easyui-textbox" validtype="length[0,200]"
                    invalidmessage="长度不可超过200" />
            </td>
            <td>
                <a class="anUnderLine" onclick="showMyWindow('选择图标', '/Home/Iconic');">
                    @Html.LabelFor(model => model.ICONIC)
                </a>
            </td>
            <td>
                <div id="Icon">
                </div>
                @Html.HiddenFor(model => model.ICONIC)
            </td>
        </tr>
        <tr class="usertablerow1">
            <td>
                @Html.LabelFor(model => model.SORT)
            </td>
            <td>
                <input type="text" name="SORT" class="easyui-numberbox" max="2147483646" invalidmessage="数值超出范围" />
            </td>
            <td>
                @Html.LabelFor(model => model.STATE)
            </td>
            <td>
                @Html.DropDownListFor(model => model.STATE, SelectListClass.GetStatus(true))
            </td>
        </tr>
        <tr  class="usertablerow2" style="height:30px;"><td> @Html.LabelFor(model => model.ISLEAF)</td><td colspan="3">@Html.RadioButtonListFor(model => model.ISLEAF, SelectListClass.GetYesOrNo(false))</td></tr>
        <tr  class="usertablerow1">
            <td>
                @Html.LabelFor(model => model.REMARK)
            </td>
            <td colspan="2" style="word-break: break-all; overflow-x: hidden;" class="remark">
                <textarea cols="30" name="REMARK" rows="3" class="easyui-validatebox" validtype="length[0,200]"
                    invalidmessage="长度不可超过200"></textarea>
            </td>
            <td>
            </td>
        </tr>
        <tr class="usertablerow2">
            <td>
                <a class="anUnderLine" onclick="showModalMany('SysOperationId','/SysOperation?view=1');">
                @Html.LabelFor(model => model.SysOperationId)</a>
            </td>
            <td colspan="3">
                <div class="selectList">
                    <ul id="checkSysOperationId">
                        @if (Model != null && !string.IsNullOrWhiteSpace(Model.SysOperationId))
                        {
                            foreach (var item13 in Model.SysOperationId.Split('^'))
                            {
                                string[] it = item13.Split('&');
                                if (it != null && it.Length == 2 && !string.IsNullOrWhiteSpace(it[0]) && !string.IsNullOrWhiteSpace(it[1]))
                                {                        
                            <li  id="@item13">
                                <img alt="删除" title="点击删除" onclick="deleteTable('@item13 ','SysOperationId');"
                                    src="/Content/Images/deleteimge.png" />
                                @it[1]</li>
                                }
                            }
                        }
                    </ul>
                    @Html.HiddenFor(model => model.SysOperationId)
                </div>
            </td>
        </tr>
        <tr class="usertablerow1">
            <td colspan="4" style="text-align: center; height: 30px;">
                 <a href='#' onclick='$("form").submit()' class="easyui-linkbutton" data-options="iconCls:'icon-add'">
                    添加</a>
                                                    <a href='#' onclick="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'"> 重置</a> 
                <a href='#' onclick="javascript:formClose();" class="easyui-linkbutton" data-options="iconCls:'icon-undo'"> 取消</a>
            </td>
        </tr>
    </table>   
}
<div id="myWindow">
</div>
@section scripts{
    <script type="text/javascript">
        function tu(tuclass) {
            $('#Icon').panel({
                iconCls: tuclass
                    , title: '您选择的图标'
                    , width: 180
            });
            $('#ICONIC').val(tuclass);

            $('#myWindow').window('close');
        }
        function showMyWindow(title, href, width, height, modal, minimizable, maximizable) {

            var icons = "";
            var flag = 19.6;
            for (var i = 1; i <= 26; i++) {
                var i0 = i < 10 ? "0" + i : i;
                for (var j = 1; j <= 20; j++) {
                    var j0 = j < 10 ? "0" + j : j;
                    icons += '<area shape="rect" coords="' + (j - 1) * flag + ',' + (i - 1) * flag + ',' + j * flag + ',' + i * flag + '" style="cursor:pointer"  onclick="tu(\'tu' + j0 + i0 + '\')" />';
                }
            }
            var ta = $('<div title="请选择图标"> <img src="../images/tabicons.gif" width="396" height="516" border="0" usemap="#Map" /><map name="Map" id="Map">' + icons + '</map></div>');
            $('#myWindow').window({
                title: title,
                width: width === undefined ? 423 : width,
                height: height === undefined ? 559 : height,
                content: ta,
                modal: modal === undefined ? true : modal,
                minimizable: minimizable === undefined ? false : minimizable,
                maximizable: maximizable === undefined ? false : maximizable,
                shadow: false,
                cache: false,
                collapsible: false,
                resizable: false,
                inline: true,
                draggable: true,
                closable: true,
                loadingMessage: '正在加载数据，请稍等片刻......'
            });

        }
</script>
}

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysMenu/Details.cshtml
@model My.RolePermission.Model.SMMENUTB
@{
    ViewBag.SubTitle = "菜单 详情";
    Layout = null;
    string ids13 = string.Empty;
    Layout = "~/Views/Shared/Save.cshtml";
}
<table id="tbCreate" class="usertableborder2" align="center">
    <tr class="usertablerow1">
        <td class="_width">
            @Html.LabelFor(model => model.NAME)
        </td>
        <td>
            <span>@Html.DisplayFor(model => model.NAME)</span>
        </td>
        <td class="_width">
            @Html.LabelFor(model => model.PARENTID)
        </td>
        <td class="width5">
            <span> @if (Model != null && Model.SMMENUTB2 != null && null != (Model.SMMENUTB2.NAME))
            {
                @Model.SMMENUTB2.NAME
            }</span>
        </td>
    </tr>
    <tr class="usertablerow2">
        <td>
            @Html.LabelFor(model => model.URL)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.URL)</span>
        </td>
        <td>
            @Html.LabelFor(model => model.ICONIC)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.ICONIC)</span>
        </td>
    </tr>
    <tr class="usertablerow1">
        <td>
            @Html.LabelFor(model => model.SORT)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.SORT)</span>
        </td>
        <td>
            @Html.LabelFor(model => model.STATE)
        </td>
        <td>
             <span>@Html.DisplayFor(model => model.STATE)</span>
        </td>
    </tr>
    <tr class="usertablerow2">
        <td>
            @Html.LabelFor(model => model.CREATEPERSON)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.CREATEPERSON)</span>
        </td>
        <td>
            @Html.LabelFor(model => model.CREATETIME)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.CREATETIME)</span>
        </td>
    </tr>
    <tr class="usertablerow1">
        <td>
            @Html.LabelFor(model => model.UPDATEPERSON)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.UPDATEPERSON)</span>
        </td>
        <td>
            @Html.LabelFor(model => model.UPDATETIME)
        </td>
        <td>
            <span> @Html.DisplayFor(model => model.UPDATETIME)</span>
        </td>
    </tr>
    <tr class="usertablerow2">
        <td>
            @Html.LabelFor(model => model.REMARK)
        </td>
        <td colspan="3" style="word-break: break-all; overflow-x: hidden;" class="remark">
            <span> @Html.ValueFor(model => model.REMARK)</span>
        </td>
    </tr>
    <tr class="usertablerow1">
        <td>
            @Html.LabelFor(model => model.SysOperationId)
        </td>
        <td colspan="3" class="remark">
            <span> @foreach (var item13 in Model.SMFUNCTB)
            {
                ids13 += item13.FUNC_NAME;
                ids13 += "，";
            }</span>
            <div class="display-field">
                @ids13.TrimEnd('，')
            </div>
        </td>
    </tr>
</table>

licaige/RolePermissionSln/RolePermissionSln/My.RolePermission.WebApp/Views/SysMenu/Edit.cshtml
@model My.RolePermission.Model.SMMENUTB
@using My.RolePermission.BLL;
@using My.RolePermission.Common.HtmlHelpers;
@using My.RolePermission.Common;
@{
    ViewBag.SubTitle = "菜单 修改";
    Layout = "~/Views/Shared/Save.cshtml";
}
@Html.ValidationSummary(true, "菜单修改不成功. 请编辑后重试")
@using (Html.BeginForm((string)ViewBag.FormAction, "SysMenu",FormMethod.Post,new {id = "form1" }))
{            
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.MENULEVEL)
            @Html.HiddenFor(model => model.CREATEPERSON)
            @Html.HiddenFor(model => model.CREATETIME)
      <table id="tbCreate" class="usertableborder" align="center">
        <tr class="usertablerow1">
            <td class="_width">
                @Html.LabelFor(model => model.NAME)
            </td>
            <td>
                <input type="text" value='@Html.ValueFor(model => model.NAME)' name="NAME" class="easyui-textbox" required="true" missingmessage="不能为空"
                    validtype="length[0,200]" invalidmessage="长度不可超过200" />
            </td>
            <td class="_width">
                <a class="anUnderLine" onclick="showModalOnly('PARENTID','/SysMenu');">
                    @Html.LabelFor(model => model.PARENTID)
                </a>
            </td>
            <td class="width5">
                     <div id="checkPARENTID">
                    @if (Model != null)
                    {
                        if (Model.PARENTID != null)
                        {
                    <table id="@Model.PARENTID" class="deleteStyle">
                        <tr>
                            <td>
                                <img alt="删除" title="点击删除" src="/Content/Images/deleteimge.png" onclick="deleteTable('@Model.PARENTID','PARENTID');" />
                            </td>
                            <td>
                                @Model.SMMENUTB2.NAME
                            </td>
                        </tr>
                    </table>
                        }
                    }
                </div>
                @Html.HiddenFor(model => model.PARENTID)
            </td>
        </tr>
        <tr class="usertablerow2">
            <td>
                @Html.LabelFor(model => model.URL)
            </td>
            <td>
                <input type="text"  value='@Html.ValueFor(model => model.URL)' name="URL" class="easyui-textbox" validtype="length[0,200]"
                    invalidmessage="长度不可超过200" />
            </td>
            <td>
                <a class="anUnderLine" onclick="showMyWindow('选择图标', '/Home/Iconic');">
                    @Html.LabelFor(model => model.ICONIC)
                </a>
            </td>
            <td>
                 @if (Model != null)
                 {
                <div id="Icon" class="easyui-panel" data-options="title: '您选择的图标'
                , width:180,iconCls:'  @Model.ICONIC'">
                </div>
                 }
                @Html.HiddenFor(model => model.ICONIC)
            </td>
        </tr>
        <tr class="usertablerow1">
            <td>
                @Html.LabelFor(model => model.SORT)
            </td>
            <td>
                <input type="text" value='@Html.ValueFor(model => model.SORT)' name="SORT" class="easyui-textbox" max="2147483646" invalidmessage="数值超出范围" />
            </td>
            <td>
                @Html.LabelFor(model => model.STATE)
            </td>
            <td>
                @Html.DropDownListFor(model => model.STATE, SelectListClass.GetStatus(true))
            </td>
        </tr>
              <tr  class="usertablerow2" style="height:30px;"><td> @Html.LabelFor(model => model.ISLEAF)</td><td colspan="3">
                 @Html.RadioButtonListFor(model => model.ISLEAF, SelectListClass.GetYesOrNo(false), true)</td></tr>
        <tr  class="usertablerow1">
            <td>
                @Html.LabelFor(model => model.REMARK)
            </td>
            <td colspan="2" style="word-break: break-all; overflow-x: hidden;" class="remark">
                <textarea cols="30" name="REMARK" rows="3" class="easyui-validatebox" validtype="length[0,200]"
                    invalidmessage="长度不可超过200">@Html.ValueFor(model => model.REMARK)</textarea>
            </td>
            <td>
            </td>
        </tr>
        <tr class="usertablerow2">
            <td>
                <a class="anUnderLine" onclick="showModalMany('SysOperationId','/SysOperation?view=1');">
                @Html.LabelFor(model => model.SysOperationId)</a>
            </td>
            <td colspan="3">
                   <div class="selectList">              
                       @if (Model != null)
                       {
                           string ids13 = string.Empty;
                            <ul id="checkSysOperationId">
                           @foreach (var item13 in Model.SMFUNCTB)
                           {
                               string item131 = string.Empty;
                               item131 += item13.FUNC_ID + "&" + item13.FUNC_NAME;
                               if (ids13.Length > 0)
                               {
                                   ids13 += "^" + item131;
                               }
                               else
                               {
                                   ids13 += item131;
                               }
                   <li id="@item131"> <img alt="删除" title="点击删除" onclick="deleteTable('@item131','SysOperationId');"
                                    src="/Content/Images/deleteimge.png" />  @item13.FUNC_NAME</li>
                           }
                            </ul>
                    <input type="hidden" value="@ids13" name="SysOperationIdOld" id="SysOperationIdOld" />
                    <input type="hidden" value="@ids13" name="SysOperationId" id="SysOperationId" />
                       }

                </div>
            </td>
        </tr>
        <tr class="usertablerow1">
            <td colspan="4" style="text-align: center; height: 30px;">
                 <a href='#' onclick='$("form").submit()' class="easyui-linkbutton" data-options="iconCls:'icon-edit'">
                    修改</a>
                                                    <a href='#' onclick="javascript:resetData()" class="easyui-linkbutton" data-options="iconCls:'icon-redo'"> 重置</a> 
                <a href='#' onclick="javascript:formClose();" class="easyui-linkbutton" data-options="iconCls:'icon-undo'"> 取消</a>
            </td>
        </tr>
    </table>   
}
    <div id="myWindow">
    </div>
@section scripts{
    <script type="text/javascript">
        function tu(tuclass) {
            $('#Icon').panel({
                iconCls: tuclass
            });
            $('#ICONIC').val(tuclass);
            $('#myWindow').window('close');
        }
        function showMyWindow(title, href, width, height, modal, minimizable, maximizable) {
            var icons = "";
            var flag = 19.6;
            for (var i = 1; i <= 26; i++) {
                var i0 = i < 10 ? "0" + i : i;
                for (var j = 1; j <= 20; j++) {
                    var j0 = j < 10 ? "0" + j : j;
                    icons += '<area shape="rect" coords="' + (j - 1) * flag + ',' + (i - 1) * flag + ',' + j * flag + ',' + i * flag + '" style="cursor:pointer"  onclick="tu(\'tu' + j0 + i0 + '\')" />';
                }
            }
            var ta = $('<div title="请选择图标" style="scroll:auto"> <img src="/Content/images/tabicons.gif" width="396" height="516" border="0" usemap="#Map" /><map name="Map" id="Map">' + icons + '</map></div>');
            $('#myWindow').window({
                title: title,
                width: width === undefined ? 423 : width,
                height: height === undefined ? 559 : height,
                content: ta,
                modal: modal === undefined ? true : modal,
                minimizable: minimizable === undefined ? false : minimizable,
                maximizable: maximizable === undefined ? false : maximizable,
                shadow: false,
                cache: false,
                collapsible: false,
                loadingMessage: '正在加载数据，请稍等片刻......'
            });
        }
    </script>
  }